--dml
INSERT INTO TBL_USUARIOS (CODIGO_USUARIO, CODIGO_TIPO_USUARIO, CODIGO_GENERO_PERSONA, CODIGO_PLAN, NOMBRE, APELLIDO, FOTO_PERFIL, FECHA_DE_NACIMIENTO, FECHA_REGISTRO, USUARIO, CORREO, CONTRASENA)
VALUES (1, 1, 1, 1, 'Juan', 'Pérez', 'foto1.jpg', TO_DATE('1990-01-01', 'YYYY-MM-DD'), SYSDATE, 'juan.perez', 'juan@example.com', 'password123');


INSERT INTO TBL_CANCIONES (CODIGO_CANCION, CODIGO_DISCOGRAFICA, NOMBRE, FECHA_PUBLICACION, DURACION, CANTIDAD_FAVORITOS, CODIGO_GENERO, URL, PORTADA)
VALUES (1, 1, 'Canción Uno', TO_DATE('2023-01-01', 'YYYY-MM-DD'), INTERVAL '3:30' HOUR TO MINUTE, 100, 1, 'http://ejemplo.com/cancion1', 'http://ejemplo.com/portada1.jpg');


INSERT INTO TBL_ARTISTAS (CODIGO_ARTISTA, GENERO_PERSONA, CODIGO_DISCOGRAFICA, FANS, FOTO_PERFIL, FECHA_NACIMIENTO, NOMBRE_ARTISTICO, NOMBRE, FECHA_REGISTRO, CORREO, CANTIDAD_ALBUM, CANTIDAD_CANCIONES, APELLIDO, FECHA_DE_NACIMIENTO, CONTRASENA)
VALUES (1, 1, 1, 1000000, 'foto_artista1.jpg', TO_DATE('1990-01-01', 'YYYY-MM-DD'), 'Artista Uno', 'Juan', SYSDATE, 'juan@example.com', 5, 20, 'Pérez', SYSTIMESTAMP, 'password123');
